- name: "backend"
  color: "0075ca"
  description: ""
- name: "bug"
  color: "d73a4a"
  description: ""
- name: "Epic"
  color: "3E4B9E"
  description: ""
- name: "frontend"
  color: "a2eeef"
  description: ""
- name: "idea"
  color: "ff6d69"
  description: ""
- name: "good-first-issue"
  color: "7057ff"
  description: ""
- name: "ready-to-merge"
  color: "d876e3"
  description: ""
- name: "roadmap"
  color: "0088CC"
  description: ""
- name: "priority:low"
  color: "FBE5C8"
  description: ""
- name: "priority:middle"
  color: "B6E5D8"
  description: ""
- name: "priority:high"
  color: "FFC2C7"
  description: ""
- name: "day:early"
  color: "E98980"
  description: ""
- name: "day:middle"
  color: "F4B9B8"
  description: ""
- name: "day:late"
  color: "EBBBB0"
  description: ""
- name: "week:early"
  color: "44FFD2"
  description: ""
- name: "week:middle"
  color: "87F6FF"
  description: ""
- name: "week:late"
  color: "DAF5FF"
  description: ""
- name: "month:early"
  color: "B4F5F0"
  description: ""
- name: "month:middle"
  color: "2CEEF0"
  description: ""
- name: "month:late"
  color: "0476D0"
  description: ""
