ignores:
  [
    "@types/segment-analytics",
    "autoprefixer",
    "firebase-*",
    "postcss",
    "postcss-import",
    "postcss-nested",
    "sharp",
    "tailwindcss",
    "@next/*",
    "@semantic-release/*",
    "@typescript-eslint/*",
    "commitizen",
    "eslint-*",
    "git-cz",
  ]
ignore-path: .gitignore
skip-missing: true
