ignores:
  [
    "autoprefixer",
    "postcss-import",
    "sharp",
    "tailwindcss",
    "vercel",
    "@semantic-release/*",
    "commitizen",
    "git-cz",
    "typescript",
  ]
ignore-path: .gitignore
skip-missing: true
