ignores:
  [
    "autoprefixer",
    "firebase-*",
    "postcss-import",
    "sharp",
    "tailwindcss",
    "@semantic-release/*",
    "commitizen",
    "eslint-import-resolver-typescript",
    "git-cz",
  ]
ignore-path: .gitignore
skip-missing: true
