name: Release
on:
  push:
    branches:
      - alpha
      - beta
      - main
jobs:
  release:
    if: github.actor != 'sentrei-bot'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_TOKEN }}
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14.4.0"
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: |
            yarn-v1-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-v1-${{ runner.os }}-
      - run: |
          yarn install --frozen-lockfile
      - run: |
          yarn run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: "sentrei-bot"
          GIT_COMMITTER_NAME: "sentrei-bot"
          GIT_AUTHOR_EMAIL: "70007101+sentrei-bot@users.noreply.github.com"
          GIT_COMMITTER_EMAIL: "70007101+sentrei-bot@users.noreply.github.com"
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - id: release
        run: |
          version=$(node -pe "require('./package.json').version")
          echo "::set-output name=release::${version}"
      - run: |
          yarn run sentry:release
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ github.repository_owner }}
          SENTRY_RELEASE: ${{ steps.release.outputs.release }}
